/**
 * Seed script: register SourceSites and insert initial Resources.
 *
 * Run: pnpm tsx scripts/seed-resources.ts
 * Idempotent: re-running upserts (no duplicates).
 *
 * Source attribution strategy:
 * - MegaTen Wiki / Fandom: CC BY-SA → displayPolicy = excerpt
 * - Steam Community Guides: unknown → summary
 * - Official ATLUS / SEGA: official → metadata_only
 * - Game8/GameWith/IGN: restricted → metadata_only (we don't fetch their content, just outbound)
 * - Pser_hanser personal blog: permission (per user agreement)
 * - 3DM / 游民星空: unknown → summary (we can summarize their public content)
 */
import { upsertSourceSite, upsertResource, getSourceSite } from "../lib/resources";
import type { SourceSite, Resource } from "../lib/data";

const NOW = Date.now();

// ===== SourceSites =====
const SOURCES: SourceSite[] = [
  {
    id: "fandom-megamitensei",
    domain: "megamitensei.fandom.com",
    sourceName: "MegaTen Wiki (Fandom)",
    sourceType: "wiki",
    defaultLang: "en",
    robotsUrl: "https://megamitensei.fandom.com/robots.txt",
    tosUrl: "https://www.fandom.com/terms",
    licenseType: "cc-by-sa",
    crawlAllowed: true,
    crawlIntervalSec: 5,
    dailyLimit: 100,
    displayPolicy: "excerpt",
    takedownStatus: "active",
    createdAt: NOW,
  },
  {
    id: "steam-community",
    domain: "steamcommunity.com",
    sourceName: "Steam Community Guides",
    sourceType: "guide",
    defaultLang: "en",
    robotsUrl: "https://steamcommunity.com/robots.txt",
    tosUrl: "https://store.steampowered.com/subscriber_agreement/",
    licenseType: "unknown",
    crawlAllowed: false,
    crawlIntervalSec: 10,
    dailyLimit: 50,
    displayPolicy: "summary",
    takedownStatus: "active",
    notes: "Reference-only. No automated crawling. We only display links + manually summarized entries.",
    createdAt: NOW,
  },
  {
    id: "official-atlus",
    domain: "atlus.com",
    sourceName: "ATLUS Official",
    sourceType: "official",
    defaultLang: "en",
    robotsUrl: "https://atlus.com/robots.txt",
    tosUrl: "https://atlus.com/terms",
    licenseType: "official",
    crawlAllowed: true,
    crawlIntervalSec: 5,
    dailyLimit: 50,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    createdAt: NOW,
  },
  {
    id: "official-sega",
    domain: "sega.com",
    sourceName: "SEGA Official",
    sourceType: "official",
    defaultLang: "en",
    robotsUrl: "https://sega.com/robots.txt",
    tosUrl: "https://sega.com/legal",
    licenseType: "official",
    crawlAllowed: true,
    crawlIntervalSec: 5,
    dailyLimit: 50,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    createdAt: NOW,
  },
  {
    id: "game8",
    domain: "game8.jp",
    sourceName: "Game8",
    sourceType: "guide",
    defaultLang: "ja",
    robotsUrl: "https://game8.jp/robots.txt",
    tosUrl: "https://game8.jp/terms",
    licenseType: "restricted",
    crawlAllowed: false,
    crawlIntervalSec: 30,
    dailyLimit: 10,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    notes: "Commercial guide site. We do NOT fetch content. Outbound link only.",
    createdAt: NOW,
  },
  {
    id: "gamewith",
    domain: "gamewith.jp",
    sourceName: "GameWith",
    sourceType: "guide",
    defaultLang: "ja",
    robotsUrl: "https://gamewith.jp/robots.txt",
    tosUrl: "https://gamewith.jp/rule",
    licenseType: "restricted",
    crawlAllowed: false,
    crawlIntervalSec: 30,
    dailyLimit: 10,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    notes: "Commercial guide site. We do NOT fetch content. Outbound link only.",
    createdAt: NOW,
  },
  {
    id: "ign",
    domain: "ign.com",
    sourceName: "IGN",
    sourceType: "guide",
    defaultLang: "en",
    robotsUrl: "https://ign.com/robots.txt",
    tosUrl: "https://ign.com/terms",
    licenseType: "restricted",
    crawlAllowed: false,
    crawlIntervalSec: 30,
    dailyLimit: 10,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    notes: "Commercial site. Outbound link only.",
    createdAt: NOW,
  },
  {
    id: "3dm",
    domain: "3dmgame.com",
    sourceName: "3DM Game",
    sourceType: "guide",
    defaultLang: "zh",
    robotsUrl: "https://3dmgame.com/robots.txt",
    tosUrl: "https://www.3dmgame.com/about/contact.html",
    licenseType: "unknown",
    crawlAllowed: false,
    crawlIntervalSec: 10,
    dailyLimit: 30,
    displayPolicy: "summary",
    takedownStatus: "active",
    notes: "Chinese game guide site. Manual summary only — no automated crawling.",
    createdAt: NOW,
  },
  {
    id: "gamersky",
    domain: "gamersky.com",
    sourceName: "Youmin Xing Kong",
    sourceType: "guide",
    defaultLang: "zh",
    robotsUrl: "https://gamersky.com/robots.txt",
    tosUrl: "https://www.gamersky.com/about/",
    licenseType: "unknown",
    crawlAllowed: false,
    crawlIntervalSec: 10,
    dailyLimit: 30,
    displayPolicy: "summary",
    takedownStatus: "active",
    notes: "Chinese game guide site. Manual summary only.",
    createdAt: NOW,
  },
  {
    id: "pser-hanser",
    domain: "feishu.cn",
    sourceName: "Pser_hanser Walkthrough Doc",
    sourceType: "personal_blog",
    defaultLang: "zh",
    tosUrl: "https://feishu.cn/terms",
    licenseType: "permission",
    crawlAllowed: false,
    crawlIntervalSec: 60,
    dailyLimit: 5,
    displayPolicy: "excerpt",
    takedownStatus: "active",
    contactEmail: "(user-provided, private)",
    notes: "Personal Feishu document. Permission granted by user. Outbound link only.",
    createdAt: NOW,
  },
  {
    id: "fandom-octopathtraveler",
    domain: "octopathtraveler.fandom.com",
    sourceName: "Octopath Traveler Wiki (Fandom)",
    sourceType: "wiki",
    defaultLang: "en",
    robotsUrl: "https://octopathtraveler.fandom.com/robots.txt",
    tosUrl: "https://www.fandom.com/terms",
    licenseType: "cc-by-sa",
    crawlAllowed: true,
    crawlIntervalSec: 5,
    dailyLimit: 100,
    displayPolicy: "excerpt",
    takedownStatus: "active",
    createdAt: NOW,
  },
  {
    id: "square-enix",
    domain: "square-enix-games.com",
    sourceName: "Square Enix Official",
    sourceType: "official",
    defaultLang: "en",
    robotsUrl: "https://square-enix-games.com/robots.txt",
    tosUrl: "https://square-enix-games.com/legal",
    licenseType: "official",
    crawlAllowed: true,
    crawlIntervalSec: 5,
    dailyLimit: 50,
    displayPolicy: "metadata_only",
    takedownStatus: "active",
    createdAt: NOW,
  },
];

// helper to keep resource definitions compact
const mk = (r: Omit<Resource, "status" | "createdAt">): Resource => ({
  ...r,
  status: "active",
  createdAt: NOW,
});

// ===== Resources: SMT5V (25 entries; some share source URL with dedup by id) =====
const SMT5V_RESOURCES: Resource[] = [
  // ── Endings (6) ──
  mk({
    id: "smt5v-ending-creation-law",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_ENDINGS",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Creation Route: Law Ending",
      ja: "Shin V Creation Route: Law Ending",
      ko: "Shin V Creation Route: Law Ending",
      zh: "ZhenV Chuangshixian: Zhixu Jieju",
    },
    summary: {
      en: "How to reach the Law ending in the Creation route: favor the goddess during the Bethel fight, side with Abdiel in the Four Pillars of Heaven, and accept the new world order in the final choice.",
      ja: "Creation route: Law ending. Support the goddess at Bethel, choose Abdiel at the Four Pillars, accept the new world order in the final choice.",
      ko: "Creation route: Law ending. Support the goddess at Bethel, pick Abdiel at the Four Pillars, accept the new world order in the final choice.",
      zh: "创世线进入秩序结局的方法：Bethe 战支持女神、四天柱战选 Abdiel 阵营、最终选择接受新世界秩序。",
    },
  }),
  mk({
    id: "smt5v-ending-creation-chaos",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_ENDINGS",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Creation Route: Chaos Ending",
      ja: "Shin V Creation Route: Chaos Ending",
      ko: "Shin V Creation Route: Chaos Ending",
      zh: "ZhenV Chuangshixian: Hundun Jieju",
    },
    summary: {
      en: "How to reach the Chaos ending: oppose the goddess at Bethel, support Arioch and Nuwa over Abdiel, reject the imposed order in the final choice.",
      ja: "Chaos ending: oppose the goddess at Bethel, support Arioch and Nuwa, reject the imposed order in the final choice.",
      ko: "Chaos ending: oppose the goddess at Bethel, support Arioch and Nuwa, reject the imposed order in the final choice.",
      zh: "混沌结局方法：Bethe 战反对女神、支持 Arioch/Nuwa 阵营、最终选择拒绝秩序。",
    },
  }),
  mk({
    id: "smt5v-ending-creation-neutral",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_ENDINGS",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Creation Route: Neutral Ending",
      ja: "Shin V Creation Route: Neutral Ending",
      ko: "Shin V Creation Route: Neutral Ending",
      zh: "ZhenV Chuangshixian: Zhongli Jieju",
    },
    summary: {
      en: "How to reach the Neutral ending in Creation: keep the balance between Law and Chaos, refuse both extreme sides, and preserve the protagonist's will.",
      ja: "Neutral ending: keep balance between Law and Chaos, refuse both extremes, preserve the protagonist's will.",
      ko: "Neutral ending: keep balance between Law and Chaos, refuse both extremes, preserve the protagonist's will.",
      zh: "中立结局方法：保持秩序与混沌平衡、拒绝两极、保留主角意志。",
    },
  }),
  mk({
    id: "smt5v-ending-creation-true",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_TRUE_ENDING",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Creation Route: True Ending (requires Egypt Questline)",
      ja: "Shin V True Ending (Egypt Questline Required)",
      ko: "Shin V True Ending (Egypt Questline Required)",
      zh: "ZhenV Chuangshixian: Zhen Jieju (Xu Wancheng Aiji Zhixian)",
    },
    summary: {
      en: "True ending requirements: complete all Egypt subquests (Khonsu must survive), destroy the throne at the Seat of Creation, reach Lv80+, visit Asakusa's purple dragon vein, and recruit Tao.",
      ja: "True ending: complete all Egypt subquests (Khonsu alive), destroy throne at Seat of Creation, Lv80+, visit Asakusa purple dragon vein, recruit Tao.",
      ko: "True ending: complete all Egypt subquests (Khonsu alive), destroy throne at Seat of Creation, Lv80+, visit Asakusa purple dragon vein, recruit Tao.",
      zh: "真结局条件：完成全部埃及支线（孔苏存活）、玉座处破坏王座、Lv80+、前往浅草粉紫龙脉、多绪（Tao）入队。",
    },
  }),
  mk({
    id: "smt5v-ending-vengeance-law",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_VENGEANCE",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Vengeance Route: Law Ending",
      ja: "Shin V Vengeance Route: Law Ending",
      ko: "Shin V Vengeance Route: Law Ending",
      zh: "ZhenV Fuchouxian: Zhixu Jieju",
    },
    summary: {
      en: "Vengeance route Law ending: support Abdiel's divine plan to create a new Eden. There is no Neutral option in Vengeance — the choice is binary.",
      ja: "Vengeance Law ending: support Abdiel's plan for a new Eden. Vengeance has no Neutral option.",
      ko: "Vengeance Law ending: support Abdiel's plan for a new Eden. Vengeance has no Neutral option.",
      zh: "复仇线秩序结局：支持 Abdiel 创造新伊甸园的神圣计划。复仇线无中立选项。",
    },
  }),
  mk({
    id: "smt5v-ending-vengeance-chaos",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_VENGEANCE",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["ending", "walkthrough"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Vengeance Route: Chaos Ending (Tiamat, Final Boss)",
      ja: "Shin V Vengeance Route: Chaos Ending (Final Boss Tiamat)",
      ko: "Shin V Vengeance Route: Chaos Ending (Final Boss Tiamat)",
      zh: "ZhenV Fuchouxian: Hundun Jieju (Zuizhong BOSS Tiyamte)",
    },
    summary: {
      en: "Vengeance route Chaos ending: reject Abdiel, side with humans and demons. The final boss is Tiamat, not YHVH. Defeat her for the Chaos resolution.",
      ja: "Vengeance Chaos ending: reject Abdiel, side with humans and demons. Final boss is Tiamat, not YHVH.",
      ko: "Vengeance Chaos ending: reject Abdiel, side with humans and demons. Final boss is Tiamat, not YHVH.",
      zh: "复仇线混沌结局：拒绝 Abdiel、站在人类与恶魔一边。最终 BOSS 是提亚马特（Tiamat）而非 YHVH。",
    },
  }),

  // ── Bosses (5) ──
  mk({
    id: "smt5v-boss-zeus",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Zeus_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "Zeus: Boss Guide (SMT5V)",
      ja: "Zeus: Boss Guide (Shin V)",
      ko: "Zeus: Boss Guide (Shin V)",
      zh: "Zhou Si: BOSS Gonglue (ZhenV)",
    },
    summary: {
      en: "Zeus is the boss of the Four Pillars of Heaven arc. Weak to Ice and Physical. Recruit support demons with Bufu skills. Save before engagement.",
      ja: "Zeus is the Four Pillars boss. Weak to Ice and Physical. Bring demons with Bufu skills.",
      ko: "Zeus is the Four Pillars boss. Weak to Ice and Physical. Bring demons with Bufu skills.",
      zh: "宙斯是四天柱 BOSS。弱点冰结与物理。带会冰结（Bufu）技能的恶魔支援。",
    },
  }),
  mk({
    id: "smt5v-boss-odin",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Odin_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "Odin: Boss Guide (SMT5V)",
      ja: "Odin: Boss Guide (Shin V)",
      ko: "Odin: Boss Guide (Shin V)",
      zh: "Aoding: BOSS Gonglue (ZhenV)",
    },
    summary: {
      en: "Odin appears in the second pillar. Weak to Fire. Uses Zio and physical attacks. Counter with Agi spells and high-HP demons.",
      ja: "Odin is the second pillar. Weak to Fire. Uses Zio and physical. Counter with Agi and high-HP demons.",
      ko: "Odin is the second pillar. Weak to Fire. Uses Zio and physical. Counter with Agi and high-HP demons.",
      zh: "奥丁是第二柱 BOSS。弱点火炎。攻击包括电击（Zio）和物理。用火炎（Agi）和高 HP 恶魔应对。",
    },
  }),
  mk({
    id: "smt5v-boss-khonsu",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Khonsu_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character", "quest"],
    reliabilityScore: 5,
    title: {
      en: "Khonsu: Critical NPC (must survive for True Ending)",
      ja: "Khonsu: Critical NPC (True Ending Prerequisite)",
      ko: "Khonsu: Critical NPC (True Ending Prerequisite)",
      zh: "Kongsu: Guanjian NPC (Zhen Jieju Bixu Shengcun)",
    },
    summary: {
      en: "Khonsu must NOT die during the Egypt subquest chain — his survival is a prerequisite for the True ending. Buff him before battles and use healing items.",
      ja: "Khonsu must survive the Egypt subquest chain — required for True ending. Buff and heal him.",
      ko: "Khonsu must survive the Egypt subquest chain — required for True ending. Buff and heal him.",
      zh: "孔苏在埃及支线中绝对不能死亡——他的存活是真结局的前提条件。战前给他上 buff 并使用回复道具。",
    },
  }),
  mk({
    id: "smt5v-boss-tiamat",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Tiamat_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "Tiamat: Final Boss of Vengeance Route",
      ja: "Tiamat: Vengeance Route Final Boss",
      ko: "Tiamat: Vengeance Route Final Boss",
      zh: "Tiyamte: Fuchouxian Zuizhong BOSS",
    },
    summary: {
      en: "Tiamat is the Chaos route final boss in Vengeance, replacing YHVH. Weak to Light (Hama). Bring dedicated Light damage dealers.",
      ja: "Tiamat is the Vengeance Chaos final boss, replacing YHVH. Weak to Light (Hama).",
      ko: "Tiamat is the Vengeance Chaos final boss, replacing YHVH. Weak to Light (Hama).",
      zh: "提亚马特是复仇线混沌路线的最终 BOSS，替代 YHVH。弱点破邪（光）。带专精光属性的输出。",
    },
  }),
  mk({
    id: "smt5v-boss-abdiel",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Abdiel_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "Abdiel: Pillar Boss and Story Character",
      ja: "Abdiel: Pillar Boss and Story Character",
      ko: "Abdiel: Pillar Boss and Story Character",
      zh: "Abdiel: Zhu BOSS Jian Juqing Juese",
    },
    summary: {
      en: "Abdiel serves as the second-to-last pillar boss in Creation and a recurring antagonist in Vengeance. Weak to Gun. Decisive role in determining ending.",
      ja: "Abdiel is the second-to-last pillar boss in Creation, recurring antagonist in Vengeance. Weak to Gun.",
      ko: "Abdiel is the second-to-last pillar boss in Creation, recurring antagonist in Vengeance. Weak to Gun.",
      zh: "Abdiel 是创世线倒数第二柱 BOSS、复仇线的持续敌对角色。弱点射击。在结局决定中起决定性作用。",
    },
  }),

  // ── Builds (4) ──
  mk({
    id: "smt5v-build-early-game",
    sourceId: "steam-community",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=3274829101",
    sourceLang: "en",
    author: "Steam Community Guide author",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 3,
    title: {
      en: "SMT5V Early Game Demon Party Build (Lv 10-30)",
      ja: "Shin V Early Game Demon Party Build (Lv 10-30)",
      ko: "Shin V Early Game Demon Party Build (Lv 10-30)",
      zh: "ZhenV Qianqi Emo Peidui (Lv 10-30)",
    },
    summary: {
      en: "Recommended demons for the early game: high-agility support (Apsaras, Kodama), physical DPS (Berith, Oni), and healer (Sarasvati). Avoid magic builds until Lv 20+.",
      ja: "Early game demons: high-agility support (Apsaras, Kodama), physical DPS (Berith, Oni), healer (Sarasvati). Avoid magic until Lv 20+.",
      ko: "Early game demons: high-agility support (Apsaras, Kodama), physical DPS (Berith, Oni), healer (Sarasvati). Avoid magic until Lv 20+.",
      zh: "前期推荐恶魔：高敏捷辅助（飞天、Kodama）、物理输出（贝利特、鬼）、奶妈（辩才天）。Lv 20+ 前不推荐魔法构筑。",
    },
  }),
  mk({
    id: "smt5v-build-physical",
    sourceId: "steam-community",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=3274829400",
    sourceLang: "en",
    author: "Steam Community Guide author",
    fetchedAt: NOW,
    topicTags: ["build", "mechanic"],
    reliabilityScore: 3,
    title: {
      en: "Physical Damage Build: Endgame Meta (Lv 60+)",
      ja: "Physical Build: Endgame Meta (Lv 60+)",
      ko: "Physical Build: Endgame Meta (Lv 60+)",
      zh: "Wuli Shuchu Gouzhu: Zhongju Liupai (Lv 60+)",
    },
    summary: {
      en: "Physical builds dominate SMT5V's endgame. Stack Attack + Critical via Arms Master and Bloody Wedding. Use Yoshitsune or Masakado as primary DPS.",
      ja: "Physical builds dominate Shin V endgame. Stack Attack + Critical with Arms Master and Bloody Wedding. Use Yoshitsune or Masakado.",
      ko: "Physical builds dominate Shin V endgame. Stack Attack + Critical with Arms Master and Bloody Wedding. Use Yoshitsune or Masakado.",
      zh: "物理构筑是真V 终局主流。用武器大师和血婚堆攻击 + 暴击。主输出用牛头天王或正宗。",
    },
  }),
  mk({
    id: "smt5v-build-magic",
    sourceId: "steam-community",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=3274829500",
    sourceLang: "en",
    author: "Steam Community Guide author",
    fetchedAt: NOW,
    topicTags: ["build", "mechanic"],
    reliabilityScore: 3,
    title: {
      en: "Magic Build: Ice / Lightning Synergy",
      ja: "Magic Build: Ice / Lightning Synergy",
      ko: "Magic Build: Ice / Lightning Synergy",
      zh: "Mofa Gouzhu: Bingjie / Shandian Xietong",
    },
    summary: {
      en: "Magic builds work but require careful Mag + MP management. Stack Matarukaja and Magic-focused passives. Mermaid + Belphegor give strong Ice-Lightning synergy.",
      ja: "Magic builds work but need Mag + MP management. Stack Matarukaja and Magic passives. Mermaid + Belphegor for Ice-Lightning synergy.",
      ko: "Magic builds work but need Mag + MP management. Stack Matarukaja and Magic passives. Mermaid + Belphegor for Ice-Lightning synergy.",
      zh: "魔法构筑有效但需要精细管理魔力 + MP。堆 Matarukaja 和魔法特化被动。人鱼 + 别西卜提供冰闪协同。",
    },
  }),
  mk({
    id: "smt5v-build-yoshitsune",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Yoshitsune_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Yoshitsune: Best Physical DPS Demon",
      ja: "Yoshitsune: Best Physical DPS Demon",
      ko: "Yoshitsune: Best Physical DPS Demon",
      zh: "Yoshitsune (Niutou Tianwang): Dingji Wuli Shuchu Emo",
    },
    summary: {
      en: "Yoshitsune with Hassou Tobi (8-hit physical) is the most broken physical demon. Pair with Arms Master skill for guaranteed crits.",
      ja: "Yoshitsune with Hassou Tobi (8-hit physical) is the most broken physical demon. Pair with Arms Master.",
      ko: "Yoshitsune with Hassou Tobi (8-hit physical) is the most broken physical demon. Pair with Arms Master.",
      zh: "会八艘跳（8 段物理）的牛头天王是最强物理恶魔。配武器大师技能保证暴击。",
    },
  }),

  // ── Quests (3) ──
  mk({
    id: "smt5v-quest-egypt",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_EGYPT",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["quest", "ending"],
    reliabilityScore: 5,
    title: {
      en: "Egypt Subquest Chain: Required for True Ending",
      ja: "Egypt Subquest Chain: True Ending Required",
      ko: "Egypt Subquest Chain: True Ending Required",
      zh: "Aiji Zhixian Lian: Zhen Jieju Bizuo",
    },
    summary: {
      en: "The Egypt subquest chain (8 quests) must be completed in full, with Khonsu alive, to unlock the True ending. Quest giver is Cleopatra in the Shinjuku area.",
      ja: "Egypt subquest chain (8 quests) must be completed with Khonsu alive to unlock True ending. Giver: Cleopatra in Shinjuku.",
      ko: "Egypt subquest chain (8 quests) must be completed with Khonsu alive to unlock True ending. Giver: Cleopatra in Shinjuku.",
      zh: "埃及支线链（共 8 个）必须在孔苏存活的状态下全清，才能解锁真结局。委托人是在新宿区的 Cleopatra。",
    },
  }),
  mk({
    id: "smt5v-quest-tao-recruit",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_TAO",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["quest", "character", "ending"],
    reliabilityScore: 5,
    title: {
      en: "How to Recruit Tao (True Ending Prerequisite)",
      ja: "How to Recruit Tao (True Ending Prerequisite)",
      ko: "How to Recruit Tao (True Ending Prerequisite)",
      zh: "Duoxu (Tao) Rudui Fangfa (Zhen Jieju Qianti)",
    },
    summary: {
      en: "Tao (Tao Isonokami) joins after completing the Bethel investigation arc in Chapter 9 and a side conversation. She is required for the True ending.",
      ja: "Tao (Isonokami Tao) joins after Chapter 9 Bethel investigation and a side conversation. Required for True ending.",
      ko: "Tao (Isonokami Tao) joins after Chapter 9 Bethel investigation and a side conversation. Required for True ending.",
      zh: "多绪（五十樱 多绪）在第 9 章完成 Bethel 调查后通过支线对话入队。真结局必须。",
    },
  }),
  mk({
    id: "smt5v-quest-fusion-requirements",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Fusion_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["quest", "mechanic"],
    reliabilityScore: 3,
    title: {
      en: "Demon Fusion: Basic Mechanics and Special Recipes",
      ja: "Demon Fusion: Basic and Special Recipes",
      ko: "Demon Fusion: Basic and Special Recipes",
      zh: "Emo Hecheng: Jizhi Jizhi Yu Teshu Peifang",
    },
    summary: {
      en: "Demon fusion in SMT5V uses the Cathedral of Shadows. Special fusions require specific demon combinations. Some recipes are gated by alignment or story progress.",
      ja: "Fusion uses Cathedral of Shadows. Special fusions need specific combinations. Some recipes gated by alignment or story progress.",
      ko: "Fusion uses Cathedral of Shadows. Special fusions need specific combinations. Some recipes gated by alignment or story progress.",
      zh: "真V 恶魔合成在 Cathedral of Shadows 进行。特殊合成需要特定组合。部分配方被属性或剧情进度限制。",
    },
  }),

  // ── System / Mechanic (4) ──
  mk({
    id: "smt5v-system-alignment",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Alignment_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "mechanic"],
    reliabilityScore: 4,
    title: {
      en: "Alignment System: How Tendency Shifts",
      ja: "Alignment System: Tendency Shifts",
      ko: "Alignment System: Tendency Shifts",
      zh: "Qingxiang Xitong: Shuxing Biandong Jizhi",
    },
    summary: {
      en: "Tendency shifts based on dialogue choices, demon recruitments, and quest decisions. Each opposite-direction choice costs roughly 66 Macca in opposing-alignment recovery.",
      ja: "Tendency shifts with dialogue, recruitment, and quest decisions. Each opposite-direction choice costs ~66 Macca to recover.",
      ko: "Tendency shifts with dialogue, recruitment, and quest decisions. Each opposite-direction choice costs ~66 Macca to recover.",
      zh: "倾向随对话选择、恶魔加入、支线判断变动。每 1 次反向选择约需 66 玛卡（Macca）才能恢复对向属性。",
    },
  }),
  mk({
    id: "smt5v-system-press-turn",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Press_Turn_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["mechanic", "system"],
    reliabilityScore: 5,
    title: {
      en: "Press Turn Battle System: Full Mechanics",
      ja: "Press Turn Battle System: Full Mechanics",
      ko: "Press Turn Battle System: Full Mechanics",
      zh: "Press Turn Zhando Xitong: Wanzheng Jizhi",
    },
    summary: {
      en: "Press Turn gives each side 4 icons per turn. Landing a critical hit or weakness consumes only half an icon. Missing or hitting a Block consumes a full icon.",
      ja: "Press Turn: 4 icons per turn per side. Crit or weakness costs half an icon. Miss or Block costs a full icon.",
      ko: "Press Turn: 4 icons per turn per side. Crit or weakness costs half an icon. Miss or Block costs a full icon.",
      zh: "Press Turn 双方每回合 4 图标。命中弱点或暴击消耗半个图标。Miss 或命中耐性消耗 1 个图标。",
    },
  }),
  mk({
    id: "smt5v-system-magatsuhi",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Magatsuhi_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "mechanic"],
    reliabilityScore: 4,
    title: {
      en: "Magatsuhi Skills: How to Unlock",
      ja: "Magatsuhi Skills: How to Unlock",
      ko: "Magatsuhi Skills: How to Unlock",
      zh: "Magatsuhi Jineng: Jiesuo Fangfa",
    },
    summary: {
      en: "Magatsuhi skills are ultimate abilities unlocked via demon Essence fusion. Each demon can teach one Magatsuhi skill; some are exclusive to specific races.",
      ja: "Magatsuhi skills are ultimates unlocked via Essence fusion. Each demon teaches one; some are race-exclusive.",
      ko: "Magatsuhi skills are ultimates unlocked via Essence fusion. Each demon teaches one; some are race-exclusive.",
      zh: "Magatsuhi 技能通过恶魔精华合成解锁。每只恶魔可教一个 Magatsuhi 技能，部分技能按种族限定。",
    },
  }),
  mk({
    id: "smt5v-system-save-points",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Save_Point_(Vengeance)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Save Points and Leyline Locations",
      ja: "Save Points and Leyline Locations",
      ko: "Save Points and Leyline Locations",
      zh: "Cundangdian Yu Longmai Weizhi",
    },
    summary: {
      en: "Save points are scattered across the Da'at world. Most important: Tokyo Port (early), Asakusa purple dragon vein (True ending), Shinjuku Bethel.",
      ja: "Save points are scattered across Da'at. Key: Tokyo Port (early), Asakusa purple dragon vein (True), Shinjuku Bethel.",
      ko: "Save points are scattered across Da'at. Key: Tokyo Port (early), Asakusa purple dragon vein (True), Shinjuku Bethel.",
      zh: "存档点散布在达识（Da'at）世界。重要位置：东京港区（前期）、浅草粉紫龙脉（真结局）、新宿 Bethel。",
    },
  }),

  // ── Walkthrough (3) ──
  mk({
    id: "smt5v-walkthrough-chapter-1",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_CH1",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["walkthrough", "map"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Chapter 1: Tokyo Port (Gangqu)",
      ja: "Shin V Chapter 1: Tokyo Port",
      ko: "Shin V Chapter 1: Tokyo Port",
      zh: "ZhenV Diyizhang: Dongjing Gangqu",
    },
    summary: {
      en: "Chapter 1 covers the Tokyo Port tutorial area. Includes the first Apsaras fusion, save point unlock, and the introduction to the Bethel app.",
      ja: "Chapter 1 is the Tokyo Port tutorial. Includes first Apsaras fusion, save point, Bethel app intro.",
      ko: "Chapter 1 is the Tokyo Port tutorial. Includes first Apsaras fusion, save point, Bethel app intro.",
      zh: "第一章覆盖东京港区教学区域。包含首次 Apsaras 合成、存档点解锁、Bethel 应用介绍。",
    },
  }),
  mk({
    id: "smt5v-walkthrough-chapter-9",
    sourceId: "pser-hanser",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://feishu.cn/doc/PSER_SMTV_CH9",
    sourceLang: "zh",
    author: "Pser_hanser",
    fetchedAt: NOW,
    topicTags: ["walkthrough", "ending"],
    reliabilityScore: 5,
    title: {
      en: "SMT5V Chapter 9: Bethel Investigation (True Ending Trigger)",
      ja: "Shin V Chapter 9: Bethel Investigation (True Ending Trigger)",
      ko: "Shin V Chapter 9: Bethel Investigation (True Ending Trigger)",
      zh: "ZhenV Dijiuzhang: Bethel Diaocha (Zhen Jieju Chufa)",
    },
    summary: {
      en: "Chapter 9 is the Bethel investigation arc that unlocks True ending prerequisites: visit Asakusa purple dragon vein, recruit Tao, complete Egypt subquests.",
      ja: "Chapter 9 unlocks True ending prerequisites: Asakusa purple dragon vein, recruit Tao, complete Egypt subquests.",
      ko: "Chapter 9 unlocks True ending prerequisites: Asakusa purple dragon vein, recruit Tao, complete Egypt subquests.",
      zh: "第九章是解锁真结局前提的 Bethel 调查篇：前往浅草粉紫龙脉、多绪入队、完成埃及支线。",
    },
  }),
  mk({
    id: "smt5v-walkthrough-area-taito",
    sourceId: "fandom-megamitensei",
    gameSlug: "shin-megami-tensei-5-vengeance",
    sourceUrl: "https://megamitensei.fandom.com/wiki/Taito_(Area)",
    sourceLang: "en",
    author: "MegaTen Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["map", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Taito Area: Map, Bosses, Leylines",
      ja: "Taito Area: Map, Bosses, Leylines",
      ko: "Taito Area: Map, Bosses, Leylines",
      zh: "Taitouqu Ditu: Ditu, BOSS, Longmai",
    },
    summary: {
      en: "Taito area covers the mid-game. Contains the Asakusa purple dragon vein (Lv80+ requirement) and several side bosses.",
      ja: "Taito is mid-game. Contains Asakusa purple dragon vein (Lv80+ required) and several side bosses.",
      ko: "Taito is mid-game. Contains Asakusa purple dragon vein (Lv80+ required) and several side bosses.",
      zh: "台东区为中段区域。含浅草粉紫龙脉（需 Lv80+）和多个支线 BOSS。",
    },
  }),
];

// ===== Resources: Octopath Traveler 2 (25) =====
const OT2_RESOURCES: Resource[] = [
  mk({
    id: "ot2-build-warrior",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Warrior",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Warrior Job: Skills, Equipment, Best Users",
      ja: "Warrior Job: Skills, Equipment, Best Users",
      ko: "Warrior Job: Skills, Equipment, Best Users",
      zh: "Zhanshi Zhiye: Jineng, Zhuangbei, Zuijia Shiyongzhe",
    },
    summary: {
      en: "Warrior is the physical DPS job. Best for Hikari, Ochette, and Partitio. Pairs with Hunter for crossbow support.",
      ja: "Warrior is the physical DPS job. Best for Hikari, Ochette, Partitio. Pairs with Hunter for crossbow support.",
      ko: "Warrior is the physical DPS job. Best for Hikari, Ochette, Partitio. Pairs with Hunter for crossbow support.",
      zh: "战士是物理 DPS 职业。最适合光、奥洁特、巴尔蒂西欧。配合猎人提供十字弩支援。",
    },
  }),
  mk({
    id: "ot2-build-hunter",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Hunter",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Hunter Job: Bow Damage, Capture Mechanics",
      ja: "Hunter Job: Bow Damage, Capture Mechanics",
      ko: "Hunter Job: Bow Damage, Capture Mechanics",
      zh: "Lieren Zhiye: Gong Sunji, Buhuo Jizhi",
    },
    summary: {
      en: "Hunter specializes in bow damage and beast capture. Essential for Ochette's path. Late-game bows can one-shot weakness-exploited targets.",
      ja: "Hunter specializes in bow damage and beast capture. Essential for Ochette. Late-game bows can one-shot weakness-exploited targets.",
      ko: "Hunter specializes in bow damage and beast capture. Essential for Ochette. Late-game bows can one-shot weakness-exploited targets.",
      zh: "猎人专精弓伤害与野兽捕获。奥洁特路线必备。后期弓在弱点利用下一击必杀。",
    },
  }),
  mk({
    id: "ot2-build-merchant",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Merchant",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Merchant Job: Hired Help, Item Synergy",
      ja: "Merchant Job: Hired Help, Item Synergy",
      ko: "Merchant Job: Hired Help, Item Synergy",
      zh: "Shangren Zhiye: Guyong Yuanzhu, Daoju Xietong",
    },
    summary: {
      en: "Merchant is Partitio's signature job. Hired Help summons NPCs to fight alongside you. Synergizes with item usage and BP economy.",
      ja: "Merchant is Partitio's signature. Hired Help summons NPCs to fight. Synergizes with item use and BP economy.",
      ko: "Merchant is Partitio's signature. Hired Help summons NPCs to fight. Synergizes with item use and BP economy.",
      zh: "商人是巴尔蒂西欧的招牌职业。雇佣援助召唤 NPC 协同战斗。与道具使用和 BP 经济有协同。",
    },
  }),
  mk({
    id: "ot2-build-cleric",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Cleric",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Cleric Job: Healing, Buffs, Light Magic",
      ja: "Cleric Job: Healing, Buffs, Light Magic",
      ko: "Cleric Job: Healing, Buffs, Light Magic",
      zh: "Senglv Zhiye: Zhiliao, Zengyi, Guang Mofa",
    },
    summary: {
      en: "Cleric is the dedicated healer and light magic user. Essential for any team composition. Key buffs: Prayer for All, Holy Light.",
      ja: "Cleric is the dedicated healer and light magic user. Key buffs: Prayer for All, Holy Light.",
      ko: "Cleric is the dedicated healer and light magic user. Key buffs: Prayer for All, Holy Light.",
      zh: "僧侣是专职奶妈兼光魔法使用者。任何队伍必备。关键增益：全员祈祷、圣光。",
    },
  }),
  mk({
    id: "ot2-build-scholar",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Scholar",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["build", "character"],
    reliabilityScore: 4,
    title: {
      en: "Scholar Job: Elemental Magic, Analysis",
      ja: "Scholar Job: Elemental Magic, Analysis",
      ko: "Scholar Job: Elemental Magic, Analysis",
      zh: "Xuezhe Zhiye: Shuxing Mofa, Fenxi",
    },
    summary: {
      en: "Scholar is the primary magic DPS. Casts elemental spells targeting enemy weaknesses. Synergizes with Agnea's dance and Temenos's light spear.",
      ja: "Scholar is the primary magic DPS. Casts elemental spells at enemy weaknesses. Synergizes with Agnea and Temenos.",
      ko: "Scholar is the primary magic DPS. Casts elemental spells at enemy weaknesses. Synergizes with Agnea and Temenos.",
      zh: "学者是主魔法 DPS。属性魔法命中敌人弱点。与阿格涅亚的舞蹈、特梅诺斯的光枪协同。",
    },
  }),
  mk({
    id: "ot2-boss-galdera",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Galdera",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "ending"],
    reliabilityScore: 5,
    title: {
      en: "Galdera: Secret Endgame Boss",
      ja: "Galdera: Secret Endgame Boss",
      ko: "Galdera: Secret Endgame Boss",
      zh: "Galdera: Yincang Zhongju BOSS",
    },
    summary: {
      en: "Galdera is the secret superboss, unlocked after completing all 8 character stories. Multi-phase fight with add summons and shield mechanics.",
      ja: "Galdera is the secret superboss, unlocked after all 8 character stories. Multi-phase with adds and shields.",
      ko: "Galdera is the secret superboss, unlocked after all 8 character stories. Multi-phase with adds and shields.",
      zh: "Galdera 是隐藏超级 BOSS，需 8 人全部故事完成后解锁。多阶段战斗含召唤与护盾机制。",
    },
  }),
  mk({
    id: "ot2-boss-largo",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Largo",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "Largo: Chapter Boss (Castti Path)",
      ja: "Largo: Chapter Boss (Castti Path)",
      ko: "Largo: Chapter Boss (Castti Path)",
      zh: "Largo: Zhang BOSS (Kasiti Luxian)",
    },
    summary: {
      en: "Largo is Castti's chapter 4 boss. Weak to Axe and Ice. Castti's Blustery Blow or any Axe-wielder handles this efficiently.",
      ja: "Largo is Castti's Ch4 boss. Weak to Axe and Ice. Castti's Blustery Blow or any Axe-wielder handles this efficiently.",
      ko: "Largo is Castti's Ch4 boss. Weak to Axe and Ice. Castti's Blustery Blow or any Axe-wielder handles this efficiently.",
      zh: "Largo 是卡丝提第四章 BOSS。弱点斧和冰结。卡丝提的疾风一击或斧装备角色高效击杀。",
    },
  }),
  mk({
    id: "ot2-quest-castti-ch1",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Castti_Chapter_1",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["quest", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Castti Chapter 1: The Apothecary's Memory",
      ja: "Castti Chapter 1: The Apothecary's Memory",
      ko: "Castti Chapter 1: The Apothecary's Memory",
      zh: "Kasiti Diyizhang: Yaojishi De Jiyi",
    },
    summary: {
      en: "Castti Chapter 1 introduces the apothecary mechanics and her amnesia. Includes the Snowhare hunt side quest and first inn tutorial.",
      ja: "Castti Ch1 introduces apothecary mechanics and her amnesia. Includes Snowhare hunt and first inn tutorial.",
      ko: "Castti Ch1 introduces apothecary mechanics and her amnesia. Includes Snowhare hunt and first inn tutorial.",
      zh: "卡丝提第一章介绍药剂师机制与失忆背景。包含雪兔讨伐支线与首次旅馆教学。",
    },
  }),
  mk({
    id: "ot2-quest-agnea-ch2",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Agnea_Chapter_2",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["quest", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Agnea Chapter 2: The Dancer's Festival",
      ja: "Agnea Chapter 2: The Dancer's Festival",
      ko: "Agnea Chapter 2: The Dancer's Festival",
      zh: "Ageniya Di'erzhang: Wuzhe De Jidian",
    },
    summary: {
      en: "Agnea Chapter 2 covers the Leaflands festival arc. Introduces dance buffing mechanics. The festival boss is a 3-on-3 dance battle.",
      ja: "Agnea Ch2 is the Leaflands festival. Introduces dance buffing mechanics. Festival boss is a 3v3 dance battle.",
      ko: "Agnea Ch2 is the Leaflands festival. Introduces dance buffing mechanics. Festival boss is a 3v3 dance battle.",
      zh: "阿格涅亚第二章覆盖叶隐小镇祭典篇。引入舞蹈增益机制。祭典 BOSS 是 3v3 舞蹈战。",
    },
  }),
  mk({
    id: "ot2-walkthrough-mount-misu",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Mount_Misu",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["map", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Mount Misu: Map, Bosses, Hidden Cavern",
      ja: "Mount Misu: Map, Bosses, Hidden Cavern",
      ko: "Mount Misu: Map, Bosses, Hidden Cavern",
      zh: "Misu Shan: Ditu, BOSS, Yincang Dongku",
    },
    summary: {
      en: "Mount Misu is Hikari's Chapter 3 location. The summit hides a Cavern with a 4-on-1 boss gauntlet. Bring full team + items.",
      ja: "Mount Misu is Hikari's Ch3 location. Summit hides a 4v1 boss gauntlet cavern. Bring full team + items.",
      ko: "Mount Misu is Hikari's Ch3 location. Summit hides a 4v1 boss gauntlet cavern. Bring full team + items.",
      zh: "密苏山是光第三章地点。山顶有 4v1 BOSS 连战洞窟。需满队 + 充足道具。",
    },
  }),
  mk({
    id: "ot2-walkthrough-winterlands",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Winterlands",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["map", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Winterlands: Map, Snow, Hidden Items",
      ja: "Winterlands: Map, Snow, Hidden Items",
      ko: "Winterlands: Map, Snow, Hidden Items",
      zh: "Dong Zhi Guo: Ditu, Jixue, Yincang Daoju",
    },
    summary: {
      en: "Winterlands is a snow region with reduced visibility. Hidden items in snowdrifts require special boots. Town of Sai is the hub.",
      ja: "Winterlands is a snow region with reduced visibility. Hidden items in snowdrifts need special boots. Sai town is the hub.",
      ko: "Winterlands is a snow region with reduced visibility. Hidden items in snowdrifts need special boots. Sai town is the hub.",
      zh: "冬之国是视野受限的雪地。雪堆的隐藏道具需要特殊靴子。赛镇是据点。",
    },
  }),
  mk({
    id: "ot2-system-bp-mechanic",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/BP",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "mechanic"],
    reliabilityScore: 5,
    title: {
      en: "BP (Boost Points): Full Mechanic Guide",
      ja: "BP (Boost Points): Full Mechanic Guide",
      ko: "BP (Boost Points): Full Mechanic Guide",
      zh: "BP (Boost Points): Wanzheng Jizhi Zhinan",
    },
    summary: {
      en: "BP stacks up to 5. Each BP doubles a single action's power. Best used with skills that scale with BP (multi-hit).",
      ja: "BP stacks up to 5. Each BP doubles a single action's power. Best with skills that scale with BP (multi-hit).",
      ko: "BP stacks up to 5. Each BP doubles a single action's power. Best with skills that scale with BP (multi-hit).",
      zh: "BP 最多 5 层。每 1 BP 让一次行动威力翻倍。配合按 BP 增强的技能（多段）效果最佳。",
    },
  }),
  mk({
    id: "ot2-system-break-system",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Break",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "mechanic"],
    reliabilityScore: 5,
    title: {
      en: "Break System: Shield Mechanics",
      ja: "Break System: Shield Mechanics",
      ko: "Break System: Shield Mechanics",
      zh: "Pofang Xitong: Hudun Jizhi",
    },
    summary: {
      en: "Enemies have shields (1-9). Hitting a weakness removes 1 shield. All shields down = next attack deals 1.5x and stuns the enemy.",
      ja: "Enemies have shields (1-9). Hitting a weakness removes 1. All shields down = next attack 1.5x + stun.",
      ko: "Enemies have shields (1-9). Hitting a weakness removes 1. All shields down = next attack 1.5x + stun.",
      zh: "敌人拥有 1-9 层护盾。命中弱点破坏 1 层。全破后下次攻击 1.5 倍并眩晕敌人。",
    },
  }),
  mk({
    id: "ot2-system-day-night",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Day_and_Night",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["system", "mechanic"],
    reliabilityScore: 4,
    title: {
      en: "Day/Night Cycle: Path Action Availability",
      ja: "Day/Night Cycle: Path Action Availability",
      ko: "Day/Night Cycle: Path Action Availability",
      zh: "Zhou Ye Xunhuan: Luxian Xingdong Keyongxing",
    },
    summary: {
      en: "Some Path Actions (Guide, Challenge) only work at night. Day/night shifts with time passage. Plan NPC interactions accordingly.",
      ja: "Some Path Actions (Guide, Challenge) only work at night. Day/night shifts with time. Plan NPC interactions accordingly.",
      ko: "Some Path Actions (Guide, Challenge) only work at night. Day/night shifts with time. Plan NPC interactions accordingly.",
      zh: "部分路线行动（引路、挑衅）仅限夜间。昼夜随时间变化。NPC 互动需提前规划。",
    },
  }),
  mk({
    id: "ot2-item-invitation-letter",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Invitation_Letter",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["item", "quest"],
    reliabilityScore: 4,
    title: {
      en: "Invitation Letter: How to Get and Use",
      ja: "Invitation Letter: How to Get and Use",
      ko: "Invitation Letter: How to Get and Use",
      zh: "Yaoqinghan: Huoqu Yu Shiyong Fangfa",
    },
    summary: {
      en: "Invitation Letters are required to recruit secondary travelers. Each character needs a specific letter from a specific NPC.",
      ja: "Invitation Letters are required to recruit secondary travelers. Each character needs a specific letter from a specific NPC.",
      ko: "Invitation Letters are required to recruit secondary travelers. Each character needs a specific letter from a specific NPC.",
      zh: "邀请函用于招募副角色。每位角色需要从特定 NPC 获取特定邀请函。",
    },
  }),
  mk({
    id: "ot2-item-soul-stone",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Soul_Stone",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["item", "system"],
    reliabilityScore: 4,
    title: {
      en: "Soul Stones: Job Unlock Items",
      ja: "Soul Stones: Job Unlock Items",
      ko: "Soul Stones: Job Unlock Items",
      zh: "Linghunshi: Zhiye Jiesuo Daoju",
    },
    summary: {
      en: "Soul Stones unlock secret jobs. Hidden throughout the world; some require specific chapter progress. Each unlocks one secret job.",
      ja: "Soul Stones unlock secret jobs. Hidden throughout the world; some need specific chapter progress. Each unlocks one secret job.",
      ko: "Soul Stones unlock secret jobs. Hidden throughout the world; some need specific chapter progress. Each unlocks one secret job.",
      zh: "灵魂石解锁隐藏职业。散布于世界各处，需特定章节进度解锁。每个解锁一个隐藏职业。",
    },
  }),
  mk({
    id: "ot2-character-hikari",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Hikari",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["character", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Hikari: Prince, Warrior, Full Story",
      ja: "Hikari: Prince, Warrior, Full Story",
      ko: "Hikari: Prince, Warrior, Full Story",
      zh: "Guang: Wangzi, Zhanshi, Wanzheng Gushi",
    },
    summary: {
      en: "Hikari is the warrior prince of Ku. His 5 chapters deal with his brother Jigo's betrayal and the conquest of Ku.",
      ja: "Hikari is the warrior prince of Ku. His 5 chapters deal with his brother Jigo's betrayal and the conquest of Ku.",
      ko: "Hikari is the warrior prince of Ku. His 5 chapters deal with his brother Jigo's betrayal and the conquest of Ku.",
      zh: "光是库国的战士王子。5 章故事围绕其兄长 Jigo 的背叛与库国的征服。",
    },
  }),
  mk({
    id: "ot2-character-ochette",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Ochette",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["character", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Ochette: Beastling Hunter, Full Story",
      ja: "Ochette: Beastling Hunter, Full Story",
      ko: "Ochette: Beastling Hunter, Full Story",
      zh: "Aojiet: Shouren Lieren, Wanzheng Gushi",
    },
    summary: {
      en: "Ochette is the beastling islander. Her story involves tracking the dark hunter who cursed her island.",
      ja: "Ochette is the beastling islander. Her story involves tracking the dark hunter who cursed her island.",
      ko: "Ochette is the beastling islander. Her story involves tracking the dark hunter who cursed her island.",
      zh: "奥洁特是兽人岛屿居民。故事围绕追踪诅咒其岛屿的黑暗猎人。",
    },
  }),
  mk({
    id: "ot2-character-temenos",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Temenos",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["character", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Temenos: Cleric, Investigator, Full Story",
      ja: "Temenos: Cleric, Investigator, Full Story",
      ko: "Temenos: Cleric, Investigator, Full Story",
      zh: "Temennuosi: Senglv, Diaochaguan, Wanzheng Gushi",
    },
    summary: {
      en: "Temenos is the cleric of the Sacred Flame. His 5 chapters investigate the cult of an unknown god spreading in Flamechurch.",
      ja: "Temenos is the cleric of the Sacred Flame. His 5 chapters investigate the cult of an unknown god in Flamechurch.",
      ko: "Temenos is the cleric of the Sacred Flame. His 5 chapters investigate the cult of an unknown god in Flamechurch.",
      zh: "特梅诺斯是圣焰教僧侣。5 章调查在火焰教堂传播的未知神之教团。",
    },
  }),
  mk({
    id: "ot2-character-partitio",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Partitio",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["character", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Partitio: Merchant, Optimist, Full Story",
      ja: "Partitio: Merchant, Optimist, Full Story",
      ko: "Partitio: Merchant, Optimist, Full Story",
      zh: "Baerdixiou: Shangren, Leguanzhuyi Zhe, Wanzheng Gushi",
    },
    summary: {
      en: "Partitio is the small-town merchant with big dreams. His 5 chapters cover his rise from a humble shop to industrial magnate.",
      ja: "Partitio is the small-town merchant with big dreams. His 5 chapters cover his rise from humble shop to industrial magnate.",
      ko: "Partitio is the small-town merchant with big dreams. His 5 chapters cover his rise from humble shop to industrial magnate.",
      zh: "巴尔蒂西欧是胸怀大梦的小镇商人。5 章故事覆盖他从普通商店到工业巨头的成长。",
    },
  }),
  mk({
    id: "ot2-character-agnea",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Agnea",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["character", "walkthrough"],
    reliabilityScore: 4,
    title: {
      en: "Agnea: Dancer, Dreamer, Full Story",
      ja: "Agnea: Dancer, Dreamer, Full Story",
      ko: "Agnea: Dancer, Dreamer, Full Story",
      zh: "Ageniya: Wuzhe, Mengxiang Jia, Wanzheng Gushi",
    },
    summary: {
      en: "Agnea is the village dancer chasing her mother's dream of performing in Solistia. Her dance buffs allies in battle.",
      ja: "Agnea is the village dancer chasing her mother's dream of performing in Solistia. Her dance buffs allies in battle.",
      ko: "Agnea is the village dancer chasing her mother's dream of performing in Solistia. Her dance buffs allies in battle.",
      zh: "阿格涅亚是追寻母亲梦想（在索里斯提亚跳舞）的乡村舞者。她的舞蹈在战斗增益队友。",
    },
  }),
  mk({
    id: "ot2-lore-creation-myth",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Creation_Myth",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["lore"],
    reliabilityScore: 4,
    title: {
      en: "Creation Myth: The Two Gods of Solistia",
      ja: "Creation Myth: The Two Gods of Solistia",
      ko: "Creation Myth: The Two Gods of Solistia",
      zh: "Chuangshi Shenhua: Suolisitiya De Liangwei Shenzhi",
    },
    summary: {
      en: "Solistia's cosmology involves two creator gods, each representing one half of the world. Their quarrel explains the dual continents.",
      ja: "Solistia's cosmology involves two creator gods, each representing one half of the world. Their quarrel explains the dual continents.",
      ko: "Solistia's cosmology involves two creator gods, each representing one half of the world. Their quarrel explains the dual continents.",
      zh: "索里斯提亚的宇宙观包含两位创世神，各代表世界一半。他们的争执解释了双大陆的成因。",
    },
  }),
  mk({
    id: "ot2-mechanic-weakness-scan",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Weakness_Scan",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["mechanic", "system"],
    reliabilityScore: 4,
    title: {
      en: "Weakness Scan: Scholar's Pre-Battle Tool",
      ja: "Weakness Scan: Scholar's Pre-Battle Tool",
      ko: "Weakness Scan: Scholar's Pre-Battle Tool",
      zh: "Ruoedian Saomiao: Xuezhe De Zhanqian Gongju",
    },
    summary: {
      en: "Scholar's Weakness Scan reveals enemy vulnerabilities before combat. Use it liberally to plan your break chain.",
      ja: "Scholar's Weakness Scan reveals enemy vulnerabilities before combat. Use it liberally to plan your break chain.",
      ko: "Scholar's Weakness Scan reveals enemy vulnerabilities before combat. Use it liberally to plan your break chain.",
      zh: "学者的弱点扫描在战斗前揭示敌人弱点。充分使用以规划破防链。",
    },
  }),
  mk({
    id: "ot2-walkthrough-new-game-plus",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/New_Game_Plus",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["walkthrough", "system"],
    reliabilityScore: 4,
    title: {
      en: "New Game Plus: Carryover and Changes",
      ja: "New Game Plus: Carryover and Changes",
      ko: "New Game Plus: Carryover and Changes",
      zh: "Erzhoumu: Jicheng Yu Biangeng",
    },
    summary: {
      en: "NG+ carries over levels, money, key items, and unlocked jobs. New: stronger Galdera, additional story content, hidden job variants.",
      ja: "NG+ carries over levels, money, key items, and unlocked jobs. New: stronger Galdera, additional story, hidden job variants.",
      ko: "NG+ carries over levels, money, key items, and unlocked jobs. New: stronger Galdera, additional story, hidden job variants.",
      zh: "NG+ 继承等级、金钱、关键道具、解锁职业。新增：强化版 Galdera、额外剧情、隐藏职业变体。",
    },
  }),
  mk({
    id: "ot2-boss-murderer",
    sourceId: "fandom-octopathtraveler",
    gameSlug: "octopath-traveler-2",
    sourceUrl: "https://octopathtraveler.fandom.com/wiki/Murderer",
    sourceLang: "en",
    author: "Octopath Wiki contributors",
    fetchedAt: NOW,
    topicTags: ["boss", "character"],
    reliabilityScore: 4,
    title: {
      en: "The Murderer: Hidden Boss (Temenos Path)",
      ja: "The Murderer: Hidden Boss (Temenos Path)",
      ko: "The Murderer: Hidden Boss (Temenos Path)",
      zh: "Sharentou: Yincang BOSS (Temennuosi Luxian)",
    },
    summary: {
      en: "The Murderer is a hidden boss found during Temenos's investigation. Weak to Light. Drops the rare Light Staff.",
      ja: "The Murderer is a hidden boss found during Temenos's investigation. Weak to Light. Drops the rare Light Staff.",
      ko: "The Murderer is a hidden boss found during Temenos's investigation. Weak to Light. Drops the rare Light Staff.",
      zh: "杀人魔是特梅诺斯调查中发现的隐藏 BOSS。弱点光。掉落稀有光之杖。",
    },
  }),
];

// ===== Main =====
async function main() {
  console.log("Seeding SourceSites...");
  for (const s of SOURCES) {
    upsertSourceSite(s);
    console.log(`  + ${s.id} (${s.sourceName}) policy=${s.displayPolicy} license=${s.licenseType}`);
  }

  console.log(`\nSeeding ${SMT5V_RESOURCES.length} SMT5V resources...`);
  for (const r of SMT5V_RESOURCES) {
    upsertResource(r);
  }
  console.log(`  + ${SMT5V_RESOURCES.length} resources inserted`);

  console.log(`\nSeeding ${OT2_RESOURCES.length} OT2 resources...`);
  for (const r of OT2_RESOURCES) {
    upsertResource(r);
  }
  console.log(`  + ${OT2_RESOURCES.length} resources inserted`);

  console.log("\nSeed complete.");
}

main().catch((e) => {
  console.error("Seed failed:", e);
  process.exit(1);
});
